# Generated by Django 4.1.1 on 2022-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=30)),
            ],
        ),
    ]
